import {StyleSheet} from 'react-native';
import {Colors} from '../../components/global/Colors';

export default StyleSheet.create({
  button: {
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
    marginHorizontal: 10,
    borderRadius: 8,
    marginTop: 10,
    width: 100,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
  },
  buttonText: {color: '#fff'},
  container: {
    flex: 1,
    backgroundColor: '#fff',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  boxContainer: {
    borderWidth: 1,
    flex: 0.5,
    justifyContent: 'center',
    margin: 20,
    borderRadius: 20,
    borderColor: Colors.primary,
    padding: 20,
  },
  infoText: {
    fontSize: 12,
    color: '#999',
  },
  inputContainer: {
    justifyContent: 'center',
    paddingHorizontal: 10,
    height: 50,
    marginTop: 10,
  },
  input: {flex: 1, backgroundColor: '#fff', width: '80%', alignSelf: 'center'},
  logo: {width: 105, height: 60},
  title: {
    color: Colors.primary,
    fontWeight: '700',
    fontSize: 16,
    textAlign: 'center',
  },
  checkboxContainer: {
    flexDirection: 'row',
    marginHorizontal: 10,
    width: 300,
    alignItems: 'center',
    marginVertical: 10,
  },
  checkbox: {
    borderWidth: 1,
    borderColor: Colors.primary,
    borderRadius: 180,
    width: 16,
    height: 16,
  },
  checkboxChecked: {
    width: 9,
    height: 9,
    backgroundColor: Colors.primary,
    borderRadius: 300,
  },
  checkboxCheckedContainer: {
    borderWidth: 1,
    borderColor: Colors.primary,
    width: 16,
    height: 16,
    borderRadius: 180,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionsContainer: {marginVertical: 10},
  resendContainer: {width: '50%', alignSelf: 'flex-end', marginVertical: 5},
});
